---
title: "Inclusion Summary"
subtitle: "Training: Trauma Informed Practice Strategies"
date: "October 2022-June 2023"

params:
  cohort: "2123"

output: 
  html_document:
    df_print: paged
    fig_width: 8
---
<!-- NEEDED INFORMATION - LOOK HERE
To make this work, we need to change the names of the cohorts of the quarter to the same name.
Do this in the "r excel file" chunk (starting line 65). Change name to YYYYQN (ex. 2123Q6).
Update cohort parameter in YAML to new quarter cohort.-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      cache = FALSE)
```

```{r library, include=FALSE}
library(tidyverse)
library(skimr)
library(janitor)
library(ggthemes)
library(hrbrthemes)
library(readxl)
library(ggtext)
library(ggalt)
library(ragg)
library(systemfonts)
library(gt)
library(knitr)
library(pagedown)
library(dplyr)
library(scales)
library(lubridate)
library(ggplot2)
library(ggrepel)
```

```{r colors, include=FALSE}
psu_green <- "#6d8d24"
psu_electricgreen <- "#cfd82d"
psu_forestgreen <- "#213921"
psu_blue <- "#008ac1"
psu_lightblue <- "#a5dff9"
psu_sand <- "#e8d3a2"
psu_stone <- "#8a8a67"
psu_yellow <- "#ffc20e"
psu_red <- "#e64927"
psu_orange <- "#f68b1f"
psu_purple <- "#650360"
```

```{r excel file, include=FALSE}
tips_inclusion <- read_excel(path = "I:\\Staff\\GSSW\\SALEM\\DATA ENTRY\\TIPS\\Archive\\TIPS 2021-2023.xlsx",
                                   sheet = "Data") %>% 
  clean_names() %>% 
  select(cohort, staff_inclusion, peer_inclusion, inclusion_text) %>% 
  mutate(cohort = as.character(cohort)) %>% 
  mutate(cohort = if_else(cohort == "202210", "2123", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202211", "2123", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202212", "2123", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202301", "2123", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202302", "2123", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202303", "2123", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202304", "2123", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202305", "2123", cohort)) %>% 
  mutate(cohort = if_else(cohort == "202306", "2123", cohort)) 
```

```{r number respondents, include=FALSE}
number_respondents_inclusion <- tips_inclusion %>% 
  filter(cohort == params$cohort) %>% 
  count(cohort) %>% 
  pull(n)
```

Training Dates:

- October 4-5, 2022
- November 8-9, 2022
- December 20-21, 2022
- January 5-6, 2023
- February 1-2, 2023
- March 29-30, 2023
- April 26-27, 2023
- May 24-25, 2023
- June 28-29, 2023

Number of Respondents: **`r number_respondents_inclusion`**

```{r}
tips_inclusion_labeled <- tips_inclusion %>% 
  mutate(staff_inclusion = recode(staff_inclusion, "1" = "Disagree",
                              "2" = "Somewhat Disagree",
                              "3" = "Neutral",
                              "4" = "Somewhat Agree",
                              "5" = "Agree")) %>% 
  mutate(peer_inclusion = recode(peer_inclusion, "1" = "Disagree",
                              "2" = "Somewhat Disagree",
                              "3" = "Neutral",
                              "4" = "Somewhat Agree",
                              "5" = "Agree"))

tips_inclusion_scales <- tips_inclusion_labeled %>%
  select(-inclusion_text) %>% 
  pivot_longer(cols = -cohort,
               names_to = "scale",
               values_to = "rating",
               values_drop_na = TRUE)
```

```{r trainers, fig.height = 3.5, fig.width = 7}
tips_inclusion_scales %>%
  filter(cohort == params$cohort,
         scale == "staff_inclusion") %>% 
  drop_na() %>% 
  count(cohort, scale, rating) %>% 
  mutate(pct = n / sum(n)) %>% 
  mutate(rating = fct_relevel(rating, c("Agree",
                     "Somewhat Agree",
                     "Neutral",
                     "Somewhat Disagree",
                     "Disagree")),
         rating = fct_explicit_na(rating, na_level = "missing")) %>% 
  ggplot(aes(x = pct,
             y = cohort,
             fill = rating)) +
    scale_fill_manual(values = c(
                     "Agree" = psu_green,
                     "Somewhat Agree" = psu_electricgreen,
                     "Neutral" = psu_sand,
                     "Somewhat Disagree" = psu_yellow,
                     "Disagree" = psu_orange)) +
  geom_col(show.legend = TRUE,
           position = "fill",
           width = 0.5) +
  geom_text_repel(aes(label = scales::percent(pct, accuracy = 1)),
            color = "black",
            size = 4,
            position = position_fill(vjust = 0.5),
            min.segment.length = 0.1) +
  scale_x_continuous(expand = expansion(add = c(0,0.2)),
                     labels = NULL) +
  scale_y_discrete(labels = NULL) +
  labs(title = "I felt respected based on my identities by <span style = 'color: #008ac1'>trainers/staff</span>",
       fill = "") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title = element_blank(),
        plot.title = element_markdown(face = "bold"))
```

```{r peers, fig.height = 3.5, fig.width = 7}
tips_inclusion_scales %>% 
  filter(cohort == params$cohort,
         scale == "peer_inclusion") %>% 
  drop_na() %>% 
  count(cohort, scale, rating) %>% 
  mutate(pct = n / sum(n)) %>% 
  mutate(rating = fct_relevel(rating, c("Agree",
                     "Somewhat Agree",
                     "Neutral",
                     "Somewhat Disagree",
                     "Disagree")),
         rating = fct_explicit_na(rating, na_level = "missing")) %>% 
  ggplot(aes(x = pct,
             y = cohort,
             fill = rating)) +
    scale_fill_manual(values = c(
                     "Agree" = psu_green,
                     "Somewhat Agree" = psu_electricgreen,
                     "Neutral" = psu_sand,
                     "Somewhat Disagree" = psu_yellow,
                     "Disagree" = psu_orange)) +
  geom_col(show.legend = TRUE,
           position = "fill",
           width = 0.5) +
  geom_text(aes(label = scales::percent(pct, accuracy = 1)),
            color = "black",
            size = 4,
            position = position_fill(vjust = 0.5)) +
  scale_x_continuous(expand = expansion(add = c(0,0.2)),
                     labels = NULL) +
  scale_y_discrete(labels = NULL) +
  labs(title = "I felt respected based on my identities by <span style = 'color: #650360'>peers</span>",
       fill = "") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title = element_blank(),
        plot.title = element_markdown(face = "bold"))
```

### Open-Ended Question Responses

*Responses on Scale Questions*

```{r agree/somewhat agree responses}
tips_inclusion_labeled %>% 
  filter(cohort == params$cohort,
         staff_inclusion %in% c("Agree", "Somewhat Agree")|peer_inclusion %in% c("Agree", "Somewhat Agree")) %>% 
  select(inclusion_text) %>% 
  drop_na()  %>% 
  distinct() %>% 
  gt() %>% 
  tab_options(table.align = "left") %>% 
  cols_label(
    inclusion_text = md("**Agree/Somewhat Agree**"))
```

```{r neutral responses}
tips_inclusion_labeled %>% 
  filter(cohort == params$cohort,
         staff_inclusion == "Neutral"|peer_inclusion == "Neutral") %>% 
  select(inclusion_text) %>% 
  drop_na()  %>% 
  distinct() %>% 
  gt() %>% 
  tab_options(table.align = "left") %>% 
  cols_label(
    inclusion_text = md("**Neutral**"))
```

```{r disagree/somewhat disagree responses}
tips_inclusion_labeled %>% 
  filter(cohort == params$cohort,
         staff_inclusion %in% c("Disagree", "Somewhat Disagree")|peer_inclusion %in% c("Disagree", "Somewhat Disagree")) %>% 
  select(inclusion_text) %>% 
  drop_na()  %>%
  distinct() %>% 
  gt() %>% 
  tab_options(table.align = "left") %>% 
  cols_label(
    inclusion_text = md("**Disagree/Somewhat Disagree**"))
```